### ISSUE TITLE
npm run dev // can not run

### ISSUE THREAD

**Issue by danielhalasz** [HackYourFutureBelgium/word-list#10]
npm ERR! Missing script: "dev"

@colevandersWands

**Comment by danielhalasz** [comment]
npm ERR! Missing script: "lint"

**Comment by colevandersWands** [comment]
moved the README from another repo, proof reading isn't always my strength 🤦

**Comment by danielhalasz** [comment]
the local linting and dev do not work.. (test and format does)

**Comment by colevandersWands** [comment]
for the dev script, I updated the README to get rid of it.  you can use liveServer or `study` so the special dev server is just extra dependencies (for now, later they can be helpful)

the linting scripts work for me locally, what kind of computer are you using?

(I also just pushed a new update with simpler scripts)
